###############################################################
#
#  This configures the robot to work with MoveIt Pro
#
###############################################################

# Baseline hardware configuration parameters for MoveIt Pro.
# [Required]
hardware:
  # Set simulated to false if you are using this as a configuration for real hardware.
  # This allows users to switch between mock and real hardware using the same configuration.
  # [Required]
  simulated: True

  # If the MoveIt Pro Agent should launch the ros2 controller node.
  # [Optional, default=True]
  launch_control_node: True

  # If the MoveIt Pro Agent should launch the robot state publisher.
  # This should be false if you are launching the robot state publisher as part of drivers.
  # [Optional, default=True]
  launch_robot_state_publisher: True

  robot_description:
    urdf:
      package: "franka_dual_arm_config"
      path: "description/franka.urdf.xacro"
    srdf:
      package: "franka_dual_arm_config"
      path: "config/moveit/franka.srdf"
    # Specify any additional parameters required for the URDF.
    # Many of these are specific to the UR descriptions packages, and can be customized as needed.
    # [Optional]
    urdf_params:
      - mujoco_model: "description/mujoco/scene.xml"
    simulated_hardware_launch_file:
      package: "moveit_studio_agent"
      path: "launch/blank.launch.py"

# Configuration files for MoveIt.
# For more information, refer to https://moveit.picknik.ai/main/doc/how_to_guides/moveit_configuration/moveit_configuration_tutorial.html
# [Required]
moveit_params:
  # Used by the Waypoint Manager to save joint states from this joint group.
  joint_group_name: "manipulator"

  ompl_planning:
    package: "franka_dual_arm_config"
    path: "config/moveit/ompl_planning.yaml"
  stomp_planning:
    package: "franka_dual_arm_config"
    path: "config/moveit/stomp_planning.yaml"
  kinematics:
    package: "franka_dual_arm_config"
    path: "config/moveit/pose_ik_distance.yaml"
  servo:
    package: "franka_dual_arm_config"
    path: "config/moveit/servo.yaml"
  sensors_3d:
    package: "franka_dual_arm_config"
    path: "config/moveit/sensors_3d.yaml"
  servo_kinematics:
    package: "franka_dual_arm_config"
    path: "config/moveit/pose_ik_speed.yaml"
  joint_limits:
    package: "franka_dual_arm_config"
    path: "config/moveit/joint_limits.yaml"
  servo_joint_limits:
    package: "franka_dual_arm_config"
    path: "config/moveit/servo_joint_limits.yaml"
  pose_jog:
    package: "franka_dual_arm_config"
    path: "config/moveit/pose_jog.yaml"

  publish:
    planning_scene: True
    geometry_updates: True
    state_updates: True
    transforms_updates: True

  trajectory_execution:
    manage_controllers: True
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 5.0
    allowed_start_tolerance: 0.01

# Configuration for loading behaviors and objectives.
# [Required]
objectives:
  # List of plugins for loading custom behaviors.
  # [Required]
  behavior_loader_plugins:
    # This plugin will load the core MoveIt Pro Behaviors.
    # Add additional plugin loaders as needed.
    core:
      - "moveit_studio::behaviors::CoreBehaviorsLoader"
      - "moveit_studio::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_studio::behaviors::ServoBehaviorsLoader"
      - "moveit_studio::behaviors::VisionBehaviorsLoader"
      - "moveit_studio::behaviors::ConverterBehaviorsLoader"
  # Specify source folder for objectives
  # [Required]
  objective_library_paths:
    core_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/core"
    motion_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/motion"
    perception_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/perception"
    #custom_objectives:
    #  package_name: "franka_dual_arm_config"
    #  relative_path: "objectives"
  # Specify the location of the saved waypoints file.
  # [Required]
  waypoints_file:
    package_name: "franka_dual_arm_config"
    relative_path: "waypoints/waypoints.yaml"
# Configuration for launching ros2_control processes.
# [Required, if using ros2_control]
ros2_control:
  config:
    package: "franka_dual_arm_config"
    path: "config/control/franka_ros2_control.yaml"
  # MoveIt Pro will load and activate these controllers at start up to ensure they are available.
  # If not specified, it is up to the user to ensure the appropriate controllers are active and available
  # for running the application.
  # [Optional, default=[]]
  controllers_active_at_startup:
    - "joint_state_broadcaster"
    - "joint_trajectory_controller"
  # Load but do not start these controllers so they can be activated later if needed.
  # [Optional, default=[]]
  controllers_inactive_at_startup:
    #- "joint_trajectory_admittance_controller"
    - "left_velocity_force_controller"
    - "right_velocity_force_controller"
    - "servo_controller"
  # Any controllers here will not be spawned by MoveIt Pro.
  # [Optional, default=[]]
  controllers_not_managed: []
  # Optionally configure remapping rules to let multiple controllers receive commands on the same topic.
  # [Optional, default=[]]
  controller_shared_topics: []
