#
#  This contains information for a unique instance of a robot.
#

# Name of the package to specialize
based_on_package: "ur5e_ridgeback_mujoco_config"
hardware:
  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    urdf:
      package: "bring_it_sim"
      path: "description/ur5e_ridgeback.xacro"
    srdf:
      package: "bring_it_sim"
      path: "config/moveit/picknik_ur.srdf"
    urdf_params:
      - joint_limits_parameters_file:
          package: "ur5e_ridgeback_mujoco_config"
          path: "config/moveit/joint_limits.yaml"
      - mujoco_model: "description/bar_scene.xml"


# Configuration for loading behaviors and objectives.
# [Required]
objectives:
  # List of plugins for loading custom behaviors.
  # [Required]
  behavior_loader_plugins:
    # This plugin will load the core MoveIt Pro Behaviors.
    # Add additional plugin loaders as needed.
    core:
      - "moveit_studio::behaviors::CoreBehaviorsLoader"
      - "moveit_studio::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_studio::behaviors::ServoBehaviorsLoader"
      - "moveit_studio::behaviors::VisionBehaviorsLoader"
  # Specify source folder for objectives
  # [Required]
  objective_library_paths:
    bring_it_sim_objectives:
      package_name: "bring_it_sim"
      relative_path: "objectives"

  # Specify the location of the saved waypoints file.
  # [Required]
  waypoints_file:
    package_name: "bring_it_sim"
    relative_path: "waypoints/ur_waypoints.yaml"

