########################################
# Goals request
########################################
std_msgs/Header header
uint8 id
string item_name
float64 timeout_sec
---
########################################
# Responses
########################################
float32 item_data
bool result
