########################################
# Goals request
########################################
std_msgs/Header header
uint8 id
---
########################################
# Responses
########################################
bool result
