########################################
# Goals request
########################################
std_msgs/Header header
uint8 id
string item_name
float32 item_data
---
########################################
# Responses
########################################
bool result
