<?xml version="1.0" encoding="utf-8" ?>
<package format="3">
  <name>kinova_vla_test_sim_behaviors</name>
  <version>6.5.0</version>
  <description>
    Behaviors for collecting color-cube stacking demonstrations
  </description>

  <maintainer email="dan.wahl@picknik.ai">Dan Wahl</maintainer>
  <author email="dan.wahl@picknik.ai">Dan Wahl</author>

  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>moveit_pro_package</build_depend>

  <depend>geometry_msgs</depend>
  <depend>moveit_pro_behavior</depend>
  <depend>moveit_pro_behavior_interface</depend>
  <depend>pluginlib</depend>
  <depend>tf2_eigen</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_clang_format</test_depend>
  <test_depend>ament_clang_tidy</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
