find_package(ament_cmake_gtest REQUIRED)

ament_add_gtest(test_behavior_plugins test_behavior_plugins.cpp)
ament_target_dependencies(test_behavior_plugins ${THIS_PACKAGE_INCLUDE_DEPENDS})

ament_add_gtest(test_compute_top_down_keyposes test_compute_top_down_keyposes.cpp)
target_link_libraries(test_compute_top_down_keyposes kinova_vla_test_sim_behaviors)
ament_target_dependencies(test_compute_top_down_keyposes ${THIS_PACKAGE_INCLUDE_DEPENDS})

ament_add_gtest(test_plan_joint_spline_through_poses test_plan_joint_spline_through_poses.cpp)
target_link_libraries(test_plan_joint_spline_through_poses kinova_vla_test_sim_behaviors)
ament_target_dependencies(test_plan_joint_spline_through_poses ${THIS_PACKAGE_INCLUDE_DEPENDS})

ament_add_gtest(test_send_gripper_command test_send_gripper_command.cpp)
target_link_libraries(test_send_gripper_command kinova_vla_test_sim_behaviors)
ament_target_dependencies(test_send_gripper_command ${THIS_PACKAGE_INCLUDE_DEPENDS})
