# Configuration file for example.launch.py
# Defines parameters for launching 0 to many (here only 1 is enabled)
# Franka Robotics components in
# namespaced or non-namespaced environments.
# Version: 1.0.0 (Updated: 2025-04-24)
#
# Note: This is a launch configuration file, not a node parameter file (see: controllers.yaml).
# Ensure all boolean values are quoted ("true" or "false") to avoid YAML parsing issues.
# Not all parameters are currently used but are included for future compatibility.
# Ensure each robot has a unique namespace to prevent topic conflicts.

left_arm: # Arbitrary identifier for the first robot (a Mnemonic) 
  arm_id: "" # Reserved for future use, unique arm (i.e. robot model) identifier
  arm_prefix: "left" # Reserved for future use (e.g., robot unique prefix)
  fake_sensor_commands: "false" # Enable fake sensor commands for simulation
  joint_sources: ["joint_states", "franka_gripper/joint_states"] # List of joint state topics
  joint_state_rate: 30 # Publishing rate for joint states (Hz)
  load_gripper: "true" # Enable Franka Gripper ("true" or "false")
  namespace: "left" # Namespace for robot, any string (empty string allowed - meaningful names recommended)
  robot_ip: "192.168.1.22" # Robot’s IP address or hostname
  urdf_file: "fr3/fr3.urdf.xacro" # Relative path to URDF in franka_description/robots
  use_fake_hardware: "false" # Use simulated hardware ("true" or "false")
  controllers_active_at_startup: ["joint_state_broadcaster", "left_velocity_force_controller"]
# Uncomment the following lines to add more robots in Namespaces
right_arm:
  arm_id: ""
  arm_prefix: "right"
  fake_sensor_commands: "false"
  joint_sources: ["joint_states", "franka_gripper/joint_states"]
  joint_state_rate: 30 
  load_gripper: "true"
  namespace: "right"
  robot_ip: "192.168.1.21"
  urdf_file: "fr3/fr3.urdf.xacro"
  use_fake_hardware: "false"
  controllers_active_at_startup: ["joint_state_broadcaster", "right_velocity_force_controller"]


