#
#  Lunar simulation configuration.
#  Inherits from phoebe_sim and overrides the MuJoCo scene
#  with a lunar environment.
#

based_on_package: "phoebe_sim"
runtime_launch_file:
  package: "lunar_sim"
  path: "launch/runtime.launch.xml"

hardware:
  robot_description:
    urdf_params:
      - mujoco_model_package: lunar_sim
      - mujoco_model: mjcf/scene.xml
