# Planning groups to use in PoseJog, and their corresponding VFC controllers.
# The number of elements in `planning_groups` and `controllers` must match.
planning_groups: ['first_manipulator', 'second_manipulator']
controllers: ['first_velocity_force_controller', 'second_velocity_force_controller']
