first_manipulator:
  kinematics_solver: slik_kinematics_plugin/SlikKinematicsPlugin
  target_tolerance: 0.001
  solve_mode: "first_found"
second_manipulator:
  kinematics_solver: slik_kinematics_plugin/SlikKinematicsPlugin
  target_tolerance: 0.001
  solve_mode: "first_found"
third_manipulator:
  kinematics_solver: slik_kinematics_plugin/SlikKinematicsPlugin
  target_tolerance: 0.001
  solve_mode: "first_found"
fourth_manipulator:
  kinematics_solver: slik_kinematics_plugin/SlikKinematicsPlugin
  target_tolerance: 0.001
  solve_mode: "first_found"
