#
#  This contains information for a unique instance of a robot.
#

# Name of the package to specialize
based_on_package: "kinova_gen3_base_config"

ros_global_params: {}

hardware:
  simulated: false
  robot_description:
    urdf:
      package: "kinova_gen3_base_hw_config"
      path: "description/picknik_kinova_gen3.xacro"
    srdf:
      package: "kinova_gen3_base_hw_config"
      path: "config/moveit/picknik_kinova_gen3.srdf"
    urdf_params:
      - arm: "gen3"
      - dof: "7"
      - vision: "true"
      - robot_ip:  "192.168.1.10"
      - gripper: "robotiq_2f_85"
      - username: "admin"
      - password: "admin"
      - port: "10000"
      - port_realtime: "10001"
      - session_inactivity_timeout_ms: "60000"
      - connection_inactivity_timeout_ms: "2000"
      - use_fake_hardware: "false"
      - fake_sensor_commands: "false"
      - use_internal_bus_gripper_comm: "true"
      - wrist_realsense: "true"
      # When set to true, use_external_cable enforces joint limits on
      # continuous joints to avoid cable wrapping
      - use_external_cable: "true"

# This Configures moveit params that are in moveit_config.py
moveit_params:
  joint_group_name: "manipulator"

  ompl_planning:
    package: "kinova_gen3_base_config"
    path: "config/moveit/ompl_planning.yaml"
  kinematics:
    package: "kinova_gen3_base_config"
    path: "config/moveit/kinematics.yaml"
  servo:
    package: "kinova_gen3_base_hw_config"
    path: "config/moveit/kinova_gen3_servo.yaml"
  sensors_3d:
    package: "kinova_gen3_base_config"
    path: "config/moveit/sensors_3d.yaml"
  joint_limits:
    package: "kinova_gen3_base_hw_config"
    path: "config/moveit/joint_limits.yaml"
  pilz_cartesian_limits:
    package: "kinova_gen3_base_hw_config"
    path: "config/moveit/pilz_cartesian_limits.yaml"

  publish:
    planning_scene: True
    geometry_updates: True
    state_updates: True
    transforms_updates: True

  trajectory_execution:
    manage_controllers: True
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 5.0
    allowed_start_tolerance: 0.01

objectives:
  objective_library_paths:
    base_kinova_hw_objectives:
      package_name: "kinova_gen3_base_hw_config"
      relative_path: "objectives"
  waypoints_file:
    package_name: "kinova_gen3_base_hw_config"
    relative_path: "waypoints/waypoints.yaml"

# This configures what controllers gets run at startup
ros2_control:
  config:
    package: "kinova_gen3_base_hw_config"
    path: "config/control/picknik_kinova_gen3.ros2_control.yaml"
  # Load and start these controllers so they can be used immediately.
  controllers_active_at_startup:
    - "robotiq_gripper_controller"
    - "joint_state_broadcaster"
    - "joint_trajectory_controller"
    - "fault_controller"
    - "servo_controller"
  # TODO: Need the ability to enable empty list of inactive controllers at startup
  # Load but do not start these controllers so they can be activated later if needed.
  controllers_inactive_at_startup:
    - "twist_controller" # this controller is currently not able to run at the same time as joint_trajectory_controller and is currently disabled in picknik_kinova_gen3.ros2_control.yaml
    - "streaming_controller"
