controller_manager:
  ros__parameters:
    update_rate: 600  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    servo_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    platform_velocity_controller:
      type: clearpath_mecanum_drive_controller/MecanumDriveController

apriltag_hardware_interface:
  ros__parameters:
    interface_names: ["linear_x_joint", "linear_y_joint", "rotational_yaw_joint"]
    vel_cmd_topic: "platform_velocity_controller/cmd_vel_unstamped"
    cmd_gain: 2.0
    command_joint_names: ["linear_x_joint", "linear_y_joint", "rotational_yaw_joint"]
    joint_state_names: ["linear_x_joint", "linear_y_joint", "rotational_yaw_joint"]
    camera_image_topics: ["left_camera/color", "right_camera/color"]
    camera_info_topics: ["left_camera/camera_info", "right_camera/camera_info"]
    apriltag_frames: ["tag1", "tag2"]
    camera_frames: ["left_camera_optical_frame", "right_camera_optical_frame"]
    apriltag_ids: [3, 4]
    base_link: "ridgeback_base_link"


platform_velocity_controller:
  ros__parameters:
    use_sim_time: False
    interface_name: velocity

    command_joint_names: ["front_left_wheel", "rear_left_wheel", "rear_right_wheel", "front_right_wheel"]

    front_left_wheel_command_joint_name: "front_left_wheel"
    front_right_wheel_command_joint_name: "front_right_wheel"
    rear_right_wheel_command_joint_name: "rear_right_wheel"
    rear_left_wheel_command_joint_name: "rear_left_wheel"

    kinematics.base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
    kinematics.wheels_radius: 0.05
    kinematics.sum_of_robot_center_projection_on_X_Y_axis: 0.4704
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    reference_timeout: 0.1
    use_stamped_vel: False

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]

    cmd_vel_timeout: 0.5

    base_frame_id: "ridgeback_base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.3
    linear.x.min_velocity: -1.3
    linear.x.max_acceleration: 1.0
    linear.x.min_acceleration: -1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    linear.y.has_velocity_limits: true
    linear.y.has_acceleration_limits: true
    linear.y.has_jerk_limits: false
    linear.y.max_velocity: 1.3
    linear.y.min_velocity: -1.3
    linear.y.max_acceleration: 1.0
    linear.y.min_acceleration: -1.0
    linear.y.max_jerk: 0.0
    linear.y.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 4.0
    angular.z.min_velocity: -4.0
    angular.z.max_acceleration: 2.0
    angular.z.min_acceleration: -2.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - robotiq_85_left_knuckle_joint
      - front_rocker
      - front_left_wheel
      - front_right_wheel
      - rear_left_wheel
      - rear_right_wheel
    interfaces:
      - position
      - velocity

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    command_joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
      shoulder_pan_joint:
        goal: 0.05
      shoulder_lift_joint:
        goal: 0.05
      elbow_joint:
        goal: 0.05
      wrist_1_joint:
        goal: 0.05
      wrist_2_joint:
        goal: 0.05
      wrist_3_joint:
        goal: 0.05
    acceleration_limits:
      shoulder_pan_joint: 10.0
      shoulder_lift_joint: 10.0
      elbow_joint: 10.0
      wrist_1_joint: 10.0
      wrist_2_joint: 10.0
      wrist_3_joint: 10.0

robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: robotiq_85_left_knuckle_joint
    allow_stalling: true
servo_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    command_joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
      shoulder_pan_joint:
        goal: 0.05
      shoulder_lift_joint:
        goal: 0.05
      elbow_joint:
        goal: 0.05
      wrist_1_joint:
        goal: 0.05
      wrist_2_joint:
        goal: 0.05
      wrist_3_joint:
        goal: 0.05
    acceleration_limits:
      shoulder_pan_joint: 10.0
      shoulder_lift_joint: 10.0
      elbow_joint: 10.0
      wrist_1_joint: 10.0
      wrist_2_joint: 10.0
      wrist_3_joint: 10.0

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: robotiq_ft_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: fts_link
