<?xml version="1.0" ?>
<package format="3">
  <name>phoebe_description</name>
  <version>8.3.0</version>

  <description>
    Shared description files for the dual arm mobile simulation and hardware
    configs.
  </description>

  <maintainer email="david.yackzan@picknik.ai">David Yackzan</maintainer>

  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>clearpath_platform_description</exec_depend>
  <exec_depend>clearpath_sensors_description</exec_depend>
  <exec_depend>ewellix_description</exec_depend>
  <exec_depend>picknik_accessories</exec_depend>
  <exec_depend>realsense2_description</exec_depend>
  <exec_depend>robotiq_description</exec_depend>
  <exec_depend>ur_description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
