SetupMTCApproachGrasp:
  world_frame_name: "world"
  arm_group_name: "manipulator"
  end_effector_group_name: "gripper"
  end_effector_name: "moveit_ee"
  hand_frame_name: "grasp_link"

  approach_distance: 0.05

  enforce_visibility_constraint: false
  camera_optical_frame_id: wrist_camera_optical_frame
  camera_field_of_view_angle: 1.0472
  sensor_z_offset: 0.0
  target_diameter: 0

SetupMTCRetractFromGrasp:
  world_frame_name: "world"
  arm_group_name: "manipulator"
  end_effector_group_name: "gripper"
  hand_frame_name: "grasp_link"
  end_effector_closed_pose_name: "close"

  approach_distance: 0.15
  lift_distance: 0.1
