find_package(ament_cmake_gtest REQUIRED)

ament_add_gtest(test_behavior_plugins test_behavior_plugins.cpp)
ament_target_dependencies(test_behavior_plugins ${THIS_PACKAGE_INCLUDE_DEPENDS})

ament_add_gtest(test_teleoperate_base_twist_mapping test_teleoperate_base_twist_mapping.cpp)
target_link_libraries(test_teleoperate_base_twist_mapping lunar_sim_behaviors)
ament_target_dependencies(test_teleoperate_base_twist_mapping ${THIS_PACKAGE_INCLUDE_DEPENDS})

ament_add_gtest(test_teleoperate_base_ros test_teleoperate_base_ros.cpp)
target_link_libraries(test_teleoperate_base_ros lunar_sim_behaviors)
ament_target_dependencies(test_teleoperate_base_ros ${THIS_PACKAGE_INCLUDE_DEPENDS})
